apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi
  namespace: argocd
  labels:
    app.kubernetes.io/name: nfs-csi
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: storage-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: nfs-csi
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    chart: v4.13.0/csi-driver-nfs
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: 4.13.0
    helm:
      valuesObject:
        controller:
          runOnControlPlane: true
          replicas: 2
        externalSnapshotter:
          enabled: true
          customResourceDefinitions:
            enabled: false
        volumeSnapshotClass:
          create: true
          name: nfs
          deletionPolicy: Delete
        storageClass:
          create: true
          name: nfs
          reclaimPolicy: Delete
          volumeBindingMode: Immediate
          mountOptions:
            - nfsvers=4.1
            - sync
            - hard
          parameters:
            server: sagittarius.starsystem.dev
            share: /mnt/storage-pool/hydra
            onDelete: delete