apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: sealed-secrets
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: sealed-secrets
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    chart: sealed-secrets/sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.18.1
    helm:
      valuesObject:
        watchForSecrets: true
        startupProbe:
          enabled: true
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
        priorityClassName: system-cluster-critical
        service:
          type: LoadBalancer
          annotations:
            metallb.io/loadBalancerIPs: 10.1.1.2
        ingress:
          enabled: true
          pathType: Prefix
          hostname: sealed-secrets.hydra.starsystem.dev
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          tls: true
        metrics:
          serviceMonitor:
            enabled: true
        pdb:
          create: true
        networkPolicy:
          enabled: true
          egress:
            enabled: true