---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-key: AgCPjPl4APjsspm0RRwWe8oIjnCxeyAnDvu0V9l1QZh5ze9O7ha09yb7TefhTN4vo+FgQLi+BQChu2gJgHJGs7cbhaMacRoYklz+IVCftip0w7nkbxRKPxs53ZzoKNxC1Kw+N89L2YxZy0ZESaPM0MfDHB5c2YRsRdWwwmJ6enb15XmGQyImKWofbPJ1onBFjrN7HZ9Eyyh4/fEgb76A1ZgNip2t8067M8g3tGHyEU/dFs4keSdH+HZq+DdaLYWfkY6bqW6MaWUngpKbaVfWiF35hrgoG8fwLLIEZtb8DUUPi+yNEzZ3+ZVD2LuZohouIFEuEnpVw7Wmr31kBctiC4PPCquzYnBjc1NI4Wc74uEk2mTqeq7hdR54+bcXtjWVoOAoBQV6sy7bczGzTt0orKKpoYzBg5ewTCJTUJ7RDnMKGXfpyJ1LLZvA5E2bK8rPNUWzdHJUpSdCmWFDafIT8EQwrn0TcW85Ur9uSlXTdJd49UHvPuAeBEX27luWD6EyZtRiQfnS3YkrwxGZ4lNb0ZEEoibiRtITdVO0DfRNaC/NdjmdRUeel86Nf9iYcmzrjCsg979DK7PmL8PI8duA31LEXH1lLwOlJPqhxo2wje1hbwIp0kpqSD+sbptTaP3YmHbvCMMp6sstxuVpzgiXhgmfhlIy1KzX2ezvwSfGa+jPJdBTVnfs2Cp+B2GMFLl8XR+I5IegiDvNrmezSHtAsY8uJWmsxKkrYmJk1WxrTyAx7QkRTIsPNl47
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: cert-manager
